spring.application.name=EmailSenderMicroservice

server.port=8084

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mariamary5034@gmail.com
spring.mail.password=figo cjxa mgbk cuuv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt.secret=r9QidC8RkI4eF8Myb8e6L3k4bU/0CZAmXHmsJSTU5+g9uE0NsmQ7QeMuv6kcsBpqYJSO7U/ya4lXUmN5EcdhtA==

