spring.application.name=UserMicroservice

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=r9QidC8RkI4eF8Myb8e6L3k4bU/0CZAmXHmsJSTU5+g9uE0NsmQ7QeMuv6kcsBpqYJSO7U/ya4lXUmN5EcdhtA==

jwt.expiration=864000000

email.service.url=http://localhost:8084/api/email
email.service.token=2xPh2wOplIq+0p8ztcaxdfEqHQ0Qsk2kyrQ5WJgIkEA=
