spring.application.name=MonitoringMicroservice

spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

server.port=8081

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=r9QidC8RkI4eF8Myb8e6L3k4bU/0CZAmXHmsJSTU5+g9uE0NsmQ7QeMuv6kcsBpqYJSO7U/ya4lXUmN5EcdhtA==

email.service.url=http://localhost:8084/api/email
email.service.token=2xPh2wOplIq+0p8ztcaxdfEqHQ0Qsk2kyrQ5WJgIkEA=

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
spring.jackson.time-zone=UTC

user.service.url=http://localhost:8080/api/user

user.service.token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzeXN0ZW1AZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWQiOjE4LCJpYXQiOjE3NTYzODMyNjMsImV4cCI6MTc1NzI0NzI2M30.7kj2UmtCsJvI07fAIwQSks9cNID3c95c_0y7KLyVd30
email.service.token.system=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzeXN0ZW1AZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWQiOjE4LCJpYXQiOjE3NTYzODMyNjMsImV4cCI6MTc1NzI0NzI2M30.7kj2UmtCsJvI07fAIwQSks9cNID3c95c_0y7KLyVd30

user.service.email=mariabutuza@gmail.com
user.service.password=3333

push.expo.url=https://exp.host/--/api/v2/push/send
push.expo.token=

